language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests --with-doctest --doctest-tests --with-coverage --cover-package table2dicts
after_success:
  coveralls
